language: node_js

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  on:
    branch: master
